version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - network-example

  aspnet-core-api-example:
    image: apolzek/aspnet-core-api-example
    ports:
      - "4000:4000"
    networks:
      - network-example
    links:
      - mongodb
    depends_on:
      - mongodb

networks:
  network-example:
    driver: bridge
